version: 0.0
os: linux
files:
  - source: /DocumentFlow
    destination: /var/www/DocumentFlow
hooks:
  BeforeInstall:
    - location: serverscripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: serverscripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: serverscripts/stop_server.sh
      timeout: 300
      runas: root