version: 0.2 # AWS指定のバージョン
phases:
  install:
    commands:
      - dotnet --version
      - dotnet restore DocumentFlow/DocumentFlow.csproj # 2003/06/14 add
      - dotnet restore DocumentFlow/DocumentFlow.sln # 2003/06/14 add
  pre_build:
    commands:
      - dotnet clean -c Release DocumentFlow/DocumentFlow.sln  # プロジェクトのクリーンアップ
  build:
    commands:
      - dotnet build -c Release DocumentFlow/DocumentFlow.sln # プロジェクトのビルド
  post_build:
    commands:
      - dotnet publish -c Release DocumentFlow/DocumentFlow.sln # プロジェクトの発行
artifacts:
  files:
    - '**/*'