version: 0.2 # AWS指定のバージョン
phases:
  install:
    commands:
      - dotnet --version
  pre_build:
    commands:
      - dotnet clean -c Release  # プロジェクトのクリーンアップ
  build:
    commands:
      - dotnet build -c Release  # プロジェクトのビルド
  post_build:
    commands:
      - dotnet publish -c Release  # プロジェクトの発行
artifacts:
  files:
    - '**/*'  # ベースディレクトリで指定されたディレクトリ配下を全て出力する
  base-directory: 'DocumentFlow/bin/Release/net6.0/publish'